rails/spothon_app_fb/config/routes.rb
SpothonAppFb::Application.routes.draw do

  match 'votes' => 'votes#index'  

end

rails/spothon_app_fb/app/models/vote.rb
class Vote < ActiveRecord::Base
end

rails/spothon_app_fb/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

rails/spothon_app_fb/app/controllers/votes_controller.rb
class VotesController < ApplicationController

  before_filter :parse_facebook_cookies  

  def parse_facebook_cookies
    @facebook_cookies ||= Koala::Facebook::OAuth.new.get_user_info_from_cookie(cookies)
  end

  # GET /votes
  def index

      require "pp"
      pp @facebook_cookies
    
    if @facebook_cookies.nil?
      render :index
    else

          access_token = @facebook_cookies['access_token']
      graph = Koala::Facebook::GraphAPI.new(access_token)
      @friends = graph.get_object("me/friends")

      require "pp"
      pp @friends

      render :votes
    end
  end

end

rails/spothon_app_fb/app/helpers/application_helper.rb
module ApplicationHelper
end

rails/spothon_app_fb/app/helpers/votes_helper.rb
module VotesHelper
end

rails/spothon_app_fb/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" lang="ja"
xmlns:og="http://ogp.me/ns#" xmlns:fb="http://www.facebook.com/2008/fbml">
<head>
<title>spothon vote</title>
<%= stylesheet_link_tag :all %>
<%= javascript_include_tag :defaults %>
<%= csrf_meta_tag %>
<meta property="og:type" content="website" />
<meta property="og:title" content="spothon vote" />
<meta property="og:url" content="http://localhost:3000/votes" />
<meta property="og:image" content="http://localhost:3000/images/hoge" />
<meta property="fb:app_id" content="<%= Facebook::APP_ID %>" />
<meta property="og:description" content="spothon vote" />
<meta name="author" content="http://spothon.com" />
<link rel="canonical" href="http://localhost:3000/votes" />
<link rel="shortcut icon" href="http://localhost:3000/images/favicon.png" />
</head>
<body>

<%= yield %>

<div id="fb-root"></div>
<script src="http://connect.facebook.net/ja_JP/all.js"></script>
<script>
  FB.init({
    appId  : '<%= Facebook::APP_ID %>',
    status : true,
    cookie : true,
    xfbml  : true
  });
  
  <% if @facebook_cookies.nil? %>
  function login(){
    FB.login(function(response) {
console.log(response);
      if (response.session) {
        location.href="http://localhost:3000/votes";
      } else {
        
      }
    }, {perms:'read_friendlists'});
  }
login();
  <% else %>
  function feed(){
   FB.ui(
       {
         method: 'feed',
         name: 'spothon vote',
         link: 'http://apps.facebook.com/spothon_vote/',
         picture: 'http://localhost:3000/images/hoge',
         message: 'hogehoge',
         description: 'あなたの友達でスポーツ王は誰だ！',
         actions: {'name':'powered by spothon Inc', 'link':'http://spothon.com'}
       });
  }
  <% end %>
</script>
</body>
</html>

rails/spothon_app_fb/app/views/votes/_form.html.erb
<%= form_for(@vote) do |f| %>
  <% if @vote.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@vote.errors.count, "error") %> prohibited this vote from being saved:</h2>

      <ul>
      <% @vote.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

rails/spothon_app_fb/app/views/votes/edit.html.erb
<h1>Editing vote</h1>

<%= render 'form' %>

<%= link_to 'Show', @vote %> |
<%= link_to 'Back', votes_path %>

rails/spothon_app_fb/app/views/votes/fb.html.erb
<html>

<style>
div#promo {
  display: none;
}
img.user {
  position: relative;
  width: 150px;
  height: 150px;
}
div#promo {
  position: absolute;
  top: 0px;
  left: 0px;
}
</style>

<body>

<div id="main">

  <div id="q"></div>
  <div id="left_q"></div>

  <div id="user_left">
    <a href="javascript:void(0);"><img class="user" src="http://a6.sphotos.ak.fbcdn.net/hphotos-ak-snc6/181726_104639412949264_100002096180152_40970_2787581_n.jpg">Toru Ikeda</a>
  </div>
  
  <div id="user_right">
    <a href="javascript:void(0);"><img class="user" src="http://photos-c.ak.fbcdn.net/hphotos-ak-snc3/23798_384265555613_695365613_4302188_3989780_a.jpg">sson</a>
  </div>

  <div id="promo">
    <img src="http://a4.sphotos.ak.fbcdn.net/hphotos-ak-ash4/270182_229802617040763_227594617261563_806924_128531_n.jpg">
  </div>
</div>

</body>
</html>

<script>

$(document).ready(function(){

  // question
  var i = 0;
  var q = [
    '野球が得意なのはどっち？',
    'どっちがサッカー好き？',
    '野球でピッチャーをやらせたら上手いのは？',
    'ズバリ！サッカー日本代表の監督にするならどっち？',
    'どっちと一緒に野球みにいきたい？',
  ];
  function append_question() {
    if ( q[i] ) {
      $("div#q").text(q[i]);
      $("div#left_q").text("あと" + ( 5 - i )+ "問");
      i++;
    }
    else {
      $("div#promo").fadeIn();
    }
  }

  // user
  $("img.user").click(function(){
    $(this).animate({"top": "-=20px"}, 500)
           .animate({"top": "+=20px"}, 500);
    append_question();
  });

  // init
  append_question();


  
});
</script>

rails/spothon_app_fb/app/views/votes/new.html.erb
<h1>New vote</h1>

<%= render 'form' %>

<%= link_to 'Back', votes_path %>

rails/spothon_app_fb/app/views/votes/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_vote_path(@vote) %> |
<%= link_to 'Back', votes_path %>

rails/spothon_app_fb/app/views/votes/votes.html.erb
<%= pp @friends %>